### ISSUE TITLE
Compilation under 4.2 kernel

### ISSUE THREAD

**Issue by GreenIOur** [heechul/memguard#2]
Hello,

I would like to test your memguard kernel module but i'm not able to build it on 4.2.x kernel version. I tried to build on an old 3.19.x kernel and it's working but i'm not able to load the module ( ins mod or mod probe are not working because of an unknown symbol ). Will you update to support kernel 4.2 ?

i post the errors during  compilation : 

`nicolas@nicolas-VOSYS-VM:~/Mem_compile/memguard$ make
make -C /lib/modules/4.2.0-25-generic/build M=/home/nicolas/Mem_compile/memguard modules
make[1]: Entering directory '/usr/src/linux-headers-4.2.0-25-generic'
  CC [M]  /home/nicolas/Mem_compile/memguard/memguard.o
/home/nicolas/Mem_compile/memguard/memguard.c:245:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘memguard_cpu_callback’
 static int __cpuinit memguard_cpu_callback(struct notifier_block *nfb,
                      ^
/home/nicolas/Mem_compile/memguard/memguard.c:263:44: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘memguard_cpu_notifier’
 static struct notifier_block __cpuinitdata memguard_cpu_notifier =
                                            ^
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘mg_nr_bwlocked_cores’:
/home/nicolas/Mem_compile/memguard/memguard.c:351:13: error: ‘struct task_struct’ has no member named ‘bwlock_val’
   if (t && t->bwlock_val > 0)
             ^
/home/nicolas/Mem_compile/memguard/memguard.c:352:11: error: ‘struct task_struct’ has no member named ‘bwlock_val’
    nr += t->bwlock_val;
           ^
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘period_timer_callback_slave’:
/home/nicolas/Mem_compile/memguard/memguard.c:668:14: error: ‘struct task_struct’ has no member named ‘bwlock_val’
    if (target->bwlock_val > 0)
              ^
/home/nicolas/Mem_compile/memguard/memguard.c:687:14: error: ‘struct task_struct’ has no member named ‘bwlock_val’
       current->bwlock_val, global->bwlocked_cores));
              ^
/home/nicolas/Mem_compile/memguard/memguard.c:23:25: note: in definition of macro ‘DEBUG_BWLOCK’
 #define DEBUG_BWLOCK(x) x
                         ^
include/linux/kernel.h:612:2: note: in expansion of macro ‘__trace_printk_check_format’
  __trace_printk_check_format(fmt, ##args);   \
  ^
include/linux/kernel.h:601:3: note: in expansion of macro ‘do_trace_printk’
   do_trace_printk(fmt, ##__VA_ARGS__); \
   ^
/home/nicolas/Mem_compile/memguard/memguard.c:685:15: note: in expansion of macro ‘trace_printk’
  DEBUG_BWLOCK(trace_printk("%s|bwlock_val %d|g->bwlocked_cores %d\n", 
               ^
/home/nicolas/Mem_compile/memguard/memguard.c:687:14: error: ‘struct task_struct’ has no member named ‘bwlock_val’
       current->bwlock_val, global->bwlocked_cores));
              ^
/home/nicolas/Mem_compile/memguard/memguard.c:23:25: note: in definition of macro ‘DEBUG_BWLOCK’
 #define DEBUG_BWLOCK(x) x
                         ^
include/linux/kernel.h:601:3: note: in expansion of macro ‘do_trace_printk’
   do_trace_printk(fmt, ##__VA_ARGS__); \
   ^
/home/nicolas/Mem_compile/memguard/memguard.c:685:15: note: in expansion of macro ‘trace_printk’
  DEBUG_BWLOCK(trace_printk("%s|bwlock_val %d|g->bwlocked_cores %d\n", 
               ^
/home/nicolas/Mem_compile/memguard/memguard.c:687:14: error: ‘struct task_struct’ has no member named ‘bwlock_val’
       current->bwlock_val, global->bwlocked_cores));
              ^
/home/nicolas/Mem_compile/memguard/memguard.c:23:25: note: in definition of macro ‘DEBUG_BWLOCK’
 #define DEBUG_BWLOCK(x) x
                         ^
include/linux/kernel.h:601:3: note: in expansion of macro ‘do_trace_printk’
   do_trace_printk(fmt, ##__VA_ARGS__); \
   ^
/home/nicolas/Mem_compile/memguard/memguard.c:685:15: note: in expansion of macro ‘trace_printk’
  DEBUG_BWLOCK(trace_printk("%s|bwlock_val %d|g->bwlocked_cores %d\n", 
               ^
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘memguard_control_show’:
/home/nicolas/Mem_compile/memguard/memguard.c:938:2: error: implicit declaration of function ‘cpulist_scnprintf’ [-Werror=implicit-function-declaration]
  cpulist_scnprintf(buf, 64, global->active_mask);
  ^
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘memguard_limit_show’:
/home/nicolas/Mem_compile/memguard/memguard.c:1041:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  struct memguard_info *global = &memguard_info;
  ^
In file included from include/linux/perf_event.h:48:0,
                 from /home/nicolas/Mem_compile/memguard/memguard.c:38:
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘init_module’:
/home/nicolas/Mem_compile/memguard/memguard.c:1302:28: error: ‘memguard_cpu_notifier’ undeclared (first use in this function)
  register_hotcpu_notifier(&memguard_cpu_notifier);
                            ^
include/linux/cpu.h:237:60: note: in definition of macro ‘register_hotcpu_notifier’
 #define register_hotcpu_notifier(nb) register_cpu_notifier(nb)
                                                            ^
/home/nicolas/Mem_compile/memguard/memguard.c:1302:28: note: each undeclared identifier is reported only once for each function it appears in
  register_hotcpu_notifier(&memguard_cpu_notifier);
                            ^
include/linux/cpu.h:237:60: note: in definition of macro ‘register_hotcpu_notifier’
 #define register_hotcpu_notifier(nb) register_cpu_notifier(nb)
                                                            ^
/home/nicolas/Mem_compile/memguard/memguard.c: In function ‘cleanup_module’:
/home/nicolas/Mem_compile/memguard/memguard.c:1366:30: error: ‘memguard_cpu_notifier’ undeclared (first use in this function)
  unregister_hotcpu_notifier(&memguard_cpu_notifier);
                              ^
include/linux/cpu.h:239:64: note: in definition of macro ‘unregister_hotcpu_notifier’
 #define unregister_hotcpu_notifier(nb) unregister_cpu_notifier(nb)
                                                                ^
cc1: some warnings being treated as errors
scripts/Makefile.build:264: recipe for target '/home/nicolas/Mem_compile/memguard/memguard.o' failed
make[2]: *** [/home/nicolas/Mem_compile/memguard/memguard.o] Error 1
Makefile:1398: recipe for target '_module_/home/nicolas/Mem_compile/memguard' failed
make[1]: *** [_module_/home/nicolas/Mem_compile/memguard] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-25-generic'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
`

thanks in advance

**Comment by GreenIOur** [comment]
The module is compiling correctly if I replace __cpuinit by __init and __cpuinitdata by __initdata. But when the module is ready ( the .ko created ) it's impossible to load the module, my pc crash and i need a hard reboot.

**Comment by heechul** [comment]
Hi,

Please try disabling BWLOCK by doing following in the memguard.c 
..
#define USE_BWLOCK 0
..

Best

**Comment by GreenIOur** [comment]
Hi,

thanks a lot for your reply !

I'm now able to compile correctly the kernel module, 
I disable BWLOCK like you said and I paste old kernel part in order to keep compatibility :

```
#define __cpuinit
#define __cpuinitdata
#define __cpuinitconst
#define __cpuexit
#define __cpuexitdata
#define __cpuexitconst
```

So now I have a "nice" memguard.ko but when i want to load the module my computer crashs and I need to hard reboot.

Best regards

[edit]

Now everything is fine just few changes to make it compile with 4.2.
Thanks for your work !

regards

**Comment by heechul** [comment]
Hi, 

"So now I have a "nice" memguard.ko but when i want to load the module my computer crashs and I need to hard reboot."

Do you still experience system crashes that require reboot? If so, could you describe your system details (processor name and .config)?

Thanks

**Comment by GreenIOur** [comment]
Hello,

Sorry for the delay of my response but I was very busy. Everything is working great ( except sometimes I don't know why memguard isn't regulating the memory bandwidth ) anyway I would like to thank you for your work, memguard is a nice memory guaranteed kernel module.
I have a question about the way you count memory traffic, I saw that you use the PMU/perf from linux kernel but I don't understand why you check "PERF_COUNT_HW_CACHE_MISSES" instead of something like 
"
  dTLB-load-misses                                   [Hardware cache event]
  dTLB-loads                                         [Hardware cache event]
  dTLB-store-misses                                  [Hardware cache event]
  dTLB-stores                                        [Hardware cache event]
"

Regards.
[edit] : all problems of non-working Memguard was due to taskset who didn't work correctly.

**Comment by moshah** [comment]
Hi,

I am having similar error, I am building it of kernel version 4.4.35 for arm based platform. 

as there is no "asm/idle.h" for "arch/arm/include/asm" I am getting these errors:

/home/root/memguard-release/memguard.c: In function 'memguard_control_show':
/home/root/memguard-release/memguard.c:968:7: warning: unused variable 'buf' [-Wunused-variable]
  char buf[64];
       ^
/home/root/memguard-release/memguard.c: In function 'init_module':
/home/root/memguard-release/memguard.c:1496:2: error: implicit declaration of function 'idle_notifier_register' [-Werror=implicit-function-declaration]
  idle_notifier_register(&memguard_idle_nb);
  ^
/home/root/memguard-release/memguard.c: In function 'cleanup_module':
/home/root/memguard-release/memguard.c:1506:2: error: implicit declaration of function 'idle_notifier_unregister' [-Werror=implicit-function-declaration]
  idle_notifier_unregister(&memguard_idle_nb);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:264: recipe for target '/home/root/memguard-release/memguard.o' failed
make[2]: *** [/home/root/memguard-release/memguard.o] Error 1
Makefile:1405: recipe for target '_module_/home/root/memguard-release' failed
make[1]: *** [_module_/home/root/memguard-release] Error 2
make[1]: Leaving directory '/usr/src/kernel'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2

kindly help me out regarding the issue, As it is very important for me.

Thank's in advance.

**Comment by Joetibz** [comment]
hello i am trying to use your software to control the amount of users that can have access to the processor at the same time, but when i run the make to get it going it throws multiple errors such as: 
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1064’; did you mean ‘-fstack-protector-strong’?
what can be the issue.
